import 'package:shared_preferences/shared_preferences.dart';

class LanguageService {
  static String currentLang = 'ar'; // اللغة الافتراضية

  // خريطة الترجمة الشاملة لكل نصوص التطبيق والرسائل الصوتية
  static final Map<String, Map<String, String>> translations = {
    // ─── شريط التنقل والعناوين الرئيسية ───
    'app_title': {
      'ar': 'سَكينة AI — المساعد الذكي للحاج',
      'en': 'Sakeenah AI — Smart Hajj Advisor',
      'ur': 'سکینہ AI — سمارٹ حج ایڈوائزر',
      'bn': 'সাকিনাহ AI — স্মার্ট হজ উপদেষ্টা',
      'tr': 'Sakeenah AI — Akıllı Hac Danışmanı',
      'fr': 'Sakeenah AI — Conseiller Hajj Intelligent',
      'id': 'Sakeenah AI — Asisten Haji Cerdas',
      'ms': 'Sakeenah AI — Penasihat Haji Pintar',
      'fa': 'سکینه AI — راهنمای هوشمند حج',
      'so': 'Sakeenah AI — Hagaha Xajka Xaasida',
      'ha': 'Sakeenah AI — Mai Jagora Hajji',
      'sw': 'Sakeenah AI — Mshauri wa Kuhimu',
    },
    'tab_home': {
      'ar': 'الرئيسية',
      'en': 'Home',
      'ur': 'ہوم',
      'bn': 'হোম',
      'tr': 'Ana Sayfa',
      'fr': 'Accueil',
      'id': 'Beranda',
      'ms': 'Laman Utama',
      'fa': 'خانه',
      'so': 'Guriga',
      'ha': 'Gida',
      'sw': 'Nyumbani',
    },
    'tab_tawaf': {
      'ar': 'الطواف والسعي',
      'en': 'Tawaf & Sa\'ee',
      'ur': 'طواف و سعی',
      'bn': 'তওয়াফ ও সাঈ',
      'tr': 'Tavaf & Sa\'y',
      'fr': 'Tawaf & Sa\'ee',
      'id': 'Tawaf & Sa\'i',
      'ms': 'Tawaf & Sa\'ie',
      'fa': 'طواف و سعی',
      'so': 'Daawafka & Sa\'yiga',
      'ha': 'Tawafi & Sa\'ayi',
      'sw': 'Tawaf & Sa\'i',
    },
    'tab_map': {
      'ar': 'المسار الآمن',
      'en': 'Safe Route',
      'ur': 'محفوظ راستہ',
      'bn': 'নিরাপদ রুট',
      'tr': 'Güvenli Rota',
      'fr': 'Itinéraire Sûr',
      'id': 'Rute Aman',
      'ms': 'Laluan Selamat',
      'fa': 'مسیر ایمن',
      'so': 'Wadada Amaan',
      'ha': 'Hanyar Aminci',
      'sw': 'Njia Salama',
    },
    'tab_emergency': {
      'ar': 'نداء الطوارئ',
      'en': 'Emergency SOS',
      'ur': 'ہنگامی امداد',
      'bn': 'জরুরী এসওএস',
      'tr': 'Acil Durum SOS',
      'fr': 'SOS Urgence',
      'id': 'SOS Darurat',
      'ms': 'SOS Kecemasan',
      'fa': 'SOS اورژانس',
      'so': 'SOS Xaaladda Degdegga',
      'ha': 'SOS Gaggawa',
      'sw': 'SOS ya Dharura',
    },

    // ─── شاشة البداية (Intro / Splash) ───
    'intro_subtitle': {
      'ar': 'رفيقك الآمن والمطمئن في الحج',
      'en': 'Your Safe & Peaceful Hajj Companion',
      'ur': 'حج میں آپ کا محفوظ اور مطمئن ساتھی',
      'bn': 'হজে আপনার নিরাপদ ও শান্তিময় সঙ্গী',
      'tr': 'Hac\'da Güvenilir Yolculuk Arkadaşınız',
      'fr': 'Votre compagnon sûr et serein pour le Hajj',
      'id': 'Teman Haji Anda yang Aman & Damai',
      'ms': 'Teman Haji Anda yang Selamat & Tenang',
      'fa': 'همراه امن و آرامش‌بخش شما در حج',
      'so': 'Saaxiibkaaga Amaan iyo Nabad ee Xajka',
      'ha': 'Abokinka Mai Aminci A Cikin Hajji',
      'sw': 'Mwenzako Salama na Mwenye Amani katika Hija',
    },
    'intro_start_btn': {
      'ar': 'ابدأ الرحلة',
      'en': 'Start Journey',
      'ur': 'سفر شروع کریں',
      'bn': 'যাত্রা শুরু করুন',
      'tr': 'Yolculuğa Başla',
      'fr': 'Commencer le Voyage',
      'id': 'Mulai Perjalanan',
      'ms': 'Mulakan Perjalanan',
      'fa': 'شروع سفر',
      'so': 'Bilow Safarka',
      'ha': 'Fara Tafiya',
      'sw': 'Anza Safari',
    },

    // ─── تبويب الصفحة الرئيسية — مراقبة الحالة الصحية ───
    'health_monitor_title': {
      'ar': 'مراقبة الحالة الصحية بالذكاء الاصطناعي',
      'en': 'AI Health Monitoring',
      'ur': 'AI سے صحت کی نگرانی',
      'bn': 'AI স্বাস্থ্য পর্যবেক্ষণ',
      'tr': 'YZ Sağlık Takibi',
      'fr': 'Surveillance Santé par IA',
      'id': 'Pemantauan Kesehatan AI',
      'ms': 'Pemantauan Kesihatan AI',
      'fa': 'پایش سلامت با هوش مصنوعی',
      'so': 'Kormeerka Caafimaadka AI',
      'ha': 'AI Kula Da Lafiya',
      'sw': 'Ufuatiliaji wa Afya wa AI',
    },
    'gait_variability': {
      'ar': 'تذبذب المشية',
      'en': 'Gait Variability',
      'ur': 'چال کی تبدیلی',
      'bn': 'চালের পরিবর্তনশীলতা',
      'tr': 'Yürüyüş Değişkenliği',
      'fr': 'Variabilité de marche',
      'id': 'Variabilitas Langkah',
      'ms': 'Variabiliti Langkah',
      'fa': 'تغییرپذیری راه رفتن',
      'so': 'Kala Duwanaanta Socodka',
      'ha': 'Bambancin Tafiya',
      'sw': 'Tofauti ya Mwendo',
    },
    'stumble_count': {
      'ar': 'حالات التعثر',
      'en': 'Stumble Count',
      'ur': 'ٹھوکروں کی تعداد',
      'bn': 'হোঁচট খাওয়ার সংখ্যা',
      'tr': 'Tökezleme Sayısı',
      'fr': 'Nombre de trébuchements',
      'id': 'Jumlah Tersandung',
      'ms': 'Kiraan Tersandung',
      'fa': 'تعداد لغزش',
      'so': 'Tiro Dhicidda',
      'ha': 'Adadin Tuntuɓe',
      'sw': 'Idadi ya Kuanguka',
    },
    // حالات الصحة
    'health_level_0': {
      'ar': 'مستقر وطبيعي ✅',
      'en': 'Stable & Normal ✅',
      'ur': 'مستحکم اور نارمل ✅',
      'bn': 'স্থিতিশীল ও স্বাভাবিক ✅',
      'tr': 'Dengeli & Normal ✅',
      'fr': 'Stable & Normal ✅',
      'id': 'Stabil & Normal ✅',
      'ms': 'Stabil & Normal ✅',
      'fa': 'پایدار و طبیعی ✅',
      'so': 'Xasiloon & Caadi ✅',
      'ha': 'Daidai & Na Yau da kullun ✅',
      'sw': 'Imara & Kawaida ✅',
    },
    'health_level_1': {
      'ar': 'يُنصح بشرب الماء والراحة 💧',
      'en': 'Drink Water & Rest Advised 💧',
      'ur': 'پانی پینے اور آرام کا مشورہ 💧',
      'bn': 'পানি পান ও বিশ্রাম নেওয়ার পরামর্শ 💧',
      'tr': 'Su için ve Dinlenin Tavsiye Edilir 💧',
      'fr': 'Buvez de l\'eau et reposez-vous 💧',
      'id': 'Minum Air & Istirahat Disarankan 💧',
      'ms': 'Minum Air & Rehat Disyorkan 💧',
      'fa': 'نوشیدن آب و استراحت توصیه می‌شود 💧',
      'so': 'Cab Biyo & Nasasho Lagu Taliyay 💧',
      'ha': 'Sha Ruwa & Hutawa An Ba Da Shawara 💧',
      'sw': 'Kunywa Maji & Kupumzika Kushauri 💧',
    },
    'health_level_2': {
      'ar': 'علامات إرهاق حراري 🌡️',
      'en': 'Signs of Heat Exhaustion 🌡️',
      'ur': 'گرمی کی تھکاوٹ کی علامات 🌡️',
      'bn': 'তাপ ক্লান্তির লক্ষণ 🌡️',
      'tr': 'Sıcak Çarpması Belirtileri 🌡️',
      'fr': 'Signes d\'épuisement par la chaleur 🌡️',
      'id': 'Tanda-tanda Kelelahan Panas 🌡️',
      'ms': 'Tanda-tanda Keletihan Haba 🌡️',
      'fa': 'علائم خستگی گرمایی 🌡️',
      'so': 'Calaamadaha Daalitaanka Kulaylka 🌡️',
      'ha': 'Alamomin Gajiyewar Zafi 🌡️',
      'sw': 'Dalili za Uchovu wa Joto 🌡️',
    },
    'health_level_3': {
      'ar': 'إجهاد حراري ودوخة شديدة 🚨',
      'en': 'Heat Stroke & Severe Dizziness 🚨',
      'ur': 'ہیٹ اسٹروک اور شدید چکر 🚨',
      'bn': 'হিট স্ট্রোক ও তীব্র মাথা ঘোরা 🚨',
      'tr': 'Isı Çarpması & Şiddetli Baş Dönmesi 🚨',
      'fr': 'Coup de chaleur & Vertige sévère 🚨',
      'id': 'Sengatan Panas & Pusing Parah 🚨',
      'ms': 'Strok Haba & Pening Teruk 🚨',
      'fa': 'ضربه گرمایی و سرگیجه شدید 🚨',
      'so': 'Kulaylka & Wareerta Xun 🚨',
      'ha': 'Bugun Zafi & Jiri Mai Tsanani 🚨',
      'sw': 'Mshtuko wa Joto & Kizunguzungu Kali 🚨',
    },
    'health_level_4': {
      'ar': 'طوارئ: تم رصد سقوط مفاجئ ⚠️',
      'en': 'Emergency: Sudden Fall Detected ⚠️',
      'ur': 'ہنگامی: اچانک گرنا محسوس ہوا ⚠️',
      'bn': 'জরুরী: হঠাৎ পতন শনাক্ত ⚠️',
      'tr': 'Acil: Ani Düşme Tespit Edildi ⚠️',
      'fr': 'Urgence : Chute soudaine détectée ⚠️',
      'id': 'Darurat: Jatuh Mendadak Terdeteksi ⚠️',
      'ms': 'Kecemasan: Jatuh Mendadak Dikesan ⚠️',
      'fa': 'اورژانس: افتادن ناگهانی تشخیص داده شد ⚠️',
      'so': 'Xaaladda Degdegga: Dhicid Lama Filaanka Ah La Ogaaday ⚠️',
      'ha': 'Gaggawa: An Gano Faduwa Kwatsam ⚠️',
      'sw': 'Dharura: Kuanguka Ghafla Kumegunduliwa ⚠️',
    },
    // نصائح الصحة
    'advice_normal': {
      'ar': 'أنت بخير والحمد لله. حافظ على شرب الماء باستمرار.',
      'en': 'You are well, Alhamdulillah. Keep drinking water regularly.',
      'ur': 'آپ ٹھیک ہیں، الحمد للہ۔ پانی پیتے رہیں۔',
      'bn': 'আপনি ভালো আছেন, আলহামদুলিল্লাহ। নিয়মিত পানি পান করুন।',
      'tr': 'İyi hissediyorsunuz, Elhamdülillah. Su içmeye devam edin.',
      'fr': 'Vous allez bien, Alhamdoulillah. Continuez à boire de l\'eau.',
      'id': 'Anda sehat, Alhamdulillah. Terus minum air secara teratur.',
      'ms': 'Anda baik-baik saja, Alhamdulillah. Terus minum air secara kerap.',
      'fa': 'حالتان خوب است، الحمدلله. به نوشیدن منظم آب ادامه دهید.',
      'so': 'Waxaad ku sugan tahay xaaladda wanaagsan, Alxamdulillaah. Sii cab biyo si joogto ah.',
      'ha': 'Kuna lafiya, Alhamdu lillahi. Ci gaba da shan ruwa akai-akai.',
      'sw': 'Uko sawa, Alhamdulillah. Endelea kunywa maji mara kwa mara.',
    },
    'advice_mild': {
      'ar': 'استرح في مكان مُظلّل واشرب ماءً بارداً. لا تتعجّل.',
      'en': 'Rest in a shaded area and drink cold water. Do not rush.',
      'ur': 'سایہ دار جگہ پر آرام کریں اور ٹھنڈا پانی پئیں۔ جلدی نہ کریں۔',
      'bn': 'ছায়াযুক্ত স্থানে বিশ্রাম নিন ও ঠান্ডা পানি পান করুন। তাড়াহুড়া করবেন না।',
      'tr': 'Gölgeli bir alanda dinlenin ve soğuk su için. Acele etmeyin.',
      'fr': 'Reposez-vous à l\'ombre et buvez de l\'eau froide. Ne vous pressez pas.',
      'id': 'Istirahatlah di tempat teduh dan minum air dingin. Jangan terburu-buru.',
      'ms': 'Berehat di tempat teduh dan minum air sejuk. Jangan tergesa-gesa.',
      'fa': 'در جای سایه استراحت کنید و آب خنک بنوشید. عجله نکنید.',
      'so': 'Naso meel hoos, cabbi biyo qabow. Ha degdeg gelin.',
      'ha': 'Huta a wuri mai inuwa ka sha ruwa mai sanyi. Kada ka yi gaggawa.',
      'sw': 'Pumzika mahali pa kivuli na kunywa maji baridi. Usifanye haraka.',
    },
    'advice_severe': {
      'ar': 'توجّه فوراً لأقرب نقطة إسعاف. اطلب المساعدة من حولك.',
      'en': 'Go immediately to the nearest first aid point. Ask for help around you.',
      'ur': 'فوری قریبی امدادی نقطے پر جائیں۔ اردگرد سے مدد مانگیں۔',
      'bn': 'অবিলম্বে নিকটতম প্রাথমিক চিকিৎসা কেন্দ্রে যান। আশেপাশের সাহায্য চান।',
      'tr': 'En yakın ilk yardım noktasına gidin. Çevrenizden yardım isteyin.',
      'fr': 'Allez immédiatement au point de premiers soins le plus proche. Demandez de l\'aide autour de vous.',
      'id': 'Segera pergi ke pos pertolongan pertama terdekat. Minta bantuan dari sekitar Anda.',
      'ms': 'Pergi segera ke pusat pertolongan cemas terdekat. Minta bantuan di sekeliling anda.',
      'fa': 'فوری به نزدیک‌ترین نقطه کمک‌های اولیه بروید. از اطرافیان کمک بخواهید.',
      'so': 'Aad isla markaa u tag meesha ugu dhaw ee gargaarka kowaad. Weydii gargaar kuwa kugu hareersan.',
      'ha': 'Je da zarar zuwa wurin taimakon farko mafi kusa. Nemi taimako daga wajenka.',
      'sw': 'Nenda mara moja katika kituo cha msaada wa kwanza kilicho karibu. Omba msaada kutoka kwa watu wanaokuzunguka.',
    },

    // ─── شاشة الموقع والـ GPS ───
    'loc_loading': {
      'ar': 'جاري تحديد موقعك...',
      'en': 'Locating you...',
      'ur': 'آپ کا مقام معلوم کیا جا رہا ہے...',
      'bn': 'আপনার অবস্থান চিহ্নিত করা হচ্ছে...',
      'tr': 'Konumunuz belirleniyor...',
      'fr': 'Localisation en cours...',
      'id': 'Menentukan lokasi Anda...',
      'ms': 'Menentukan lokasi anda...',
      'fa': 'در حال تعیین موقعیت شما...',
      'so': 'Goobta lagaa helayaa...',
      'ha': 'Ana nemo wurinka...',
      'sw': 'Inatafuta mahali pako...',
    },
    'loc_perm_denied': {
      'ar': 'يرجى تفعيل صلاحية الموقع من الإعدادات.',
      'en': 'Please enable location permission from settings.',
      'ur': 'براہ کرم سیٹنگز سے لوکیشن کی اجازت فعال کریں۔',
      'bn': 'অনুগ্রহ করে সেটিংস থেকে লোকেশন পারমিশন চালু করুন।',
      'tr': 'Lütfen ayarlardan konum iznini etkinleştirin.',
      'fr': 'Veuillez activer la permission de localisation dans les paramètres.',
      'id': 'Harap aktifkan izin lokasi dari pengaturan.',
      'ms': 'Sila aktifkan kebenaran lokasi dari tetapan.',
      'fa': 'لطفاً مجوز موقعیت را از تنظیمات فعال کنید.',
      'so': 'Fadlan ka fur oggolaanshaha goobta goobaha dejinta.',
      'ha': 'Don Allah ka kunna izinin wuri daga saitunan.',
      'sw': 'Tafadhali wezesha ruhusa ya mahali kutoka mipangilio.',
    },
    'no_points_type': {
      'ar': 'لا توجد نقاط من هذا النوع.',
      'en': 'No points found for this category.',
      'ur': 'اس زمرے کے لیے کوئی مقامات نہیں ملے۔',
      'bn': 'এই বিভাগে কোনো স্থান পাওয়া যায়নি।',
      'tr': 'Bu kategori için nokta bulunamadı.',
      'fr': 'Aucun point trouvé pour cette catégorie.',
      'id': 'Tidak ada titik ditemukan untuk kategori ini.',
      'ms': 'Tiada titik ditemui untuk kategori ini.',
      'fa': 'هیچ نقطه‌ای برای این دسته‌بندی پیدا نشد.',
      'so': 'Wax meel ah lama helin qeybtan.',
      'ha': 'Ba a sami wuri ba don wannan rukuni.',
      'sw': 'Hakuna pointi zilizopatikana kwa kategoria hii.',
    },
    'nearest_point': {
      'ar': 'أقرب نقطة: ',
      'en': 'Nearest point: ',
      'ur': 'قریب ترین مقام: ',
      'bn': 'নিকটবর্তী স্থান: ',
      'tr': 'En yakın nokta: ',
      'fr': 'Point le plus proche : ',
      'id': 'Titik terdekat: ',
      'ms': 'Titik terdekat: ',
      'fa': 'نزدیک‌ترین نقطه: ',
      'so': 'Meesha ugu dhow: ',
      'ha': 'Wurin da ya fi kusa: ',
      'sw': 'Pointi iliyo karibu zaidi: ',
    },
    'distance': {
      'ar': 'المسافة: ',
      'en': 'Distance: ',
      'ur': 'فاصلہ: ',
      'bn': 'দূরত্ব: ',
      'tr': 'Mesafe: ',
      'fr': 'Distance : ',
      'id': 'Jarak: ',
      'ms': 'Jarak: ',
      'fa': 'فاصله: ',
      'so': 'Fogaanta: ',
      'ha': 'Nisa: ',
      'sw': 'Umbali: ',
    },
    'km': {
      'ar': 'كم',
      'en': 'km',
      'ur': 'کلومیٹر',
      'bn': 'কিমি',
      'tr': 'km',
      'fr': 'km',
      'id': 'km',
      'ms': 'km',
      'fa': 'کیلومتر',
      'so': 'km',
      'ha': 'km',
      'sw': 'km',
    },
    'meter': {
      'ar': 'متر',
      'en': 'meters',
      'ur': 'میٹر',
      'bn': 'মিটার',
      'tr': 'metre',
      'fr': 'mètres',
      'id': 'meter',
      'ms': 'meter',
      'fa': 'متر',
      'so': 'mitir',
      'ha': 'mitoci',
      'sw': 'mita',
    },

    // ─── الفلاتر ونقاط الخدمات ───
    'filter_all': {
      'ar': 'الكل',
      'en': 'All',
      'ur': 'سب',
      'bn': 'সব',
      'tr': 'Hepsi',
      'fr': 'Tout',
      'id': 'Semua',
      'ms': 'Semua',
      'fa': 'همه',
      'so': 'Dhami',
      'ha': 'Duka',
      'sw': 'Zote',
    },
    'filter_hospital': {
      'ar': 'مستشفى',
      'en': 'Hospital',
      'ur': 'ہسپتال',
      'bn': 'হাসপাতাল',
      'tr': 'Hastane',
      'fr': 'Hôpital',
      'id': 'Rumah Sakit',
      'ms': 'Hospital',
      'fa': 'بیمارستان',
      'so': 'Isbitaalka',
      'ha': 'Asibiti',
      'sw': 'Hospitali',
    },
    'filter_ambulance': {
      'ar': 'إسعاف',
      'en': 'Ambulance',
      'ur': 'ایمبولینس',
      'bn': 'অ্যাম্বুলেন্স',
      'tr': 'Ambulans',
      'fr': 'Ambulance',
      'id': 'Ambulans',
      'ms': 'Ambulans',
      'fa': 'آمبولانس',
      'so': 'Ambalaansta',
      'ha': 'Motar Asibiti',
      'sw': 'Ambulensi',
    },
    'filter_water': {
      'ar': 'مياه',
      'en': 'Water',
      'ur': 'پانی',
      'bn': 'পানি',
      'tr': 'Su',
      'fr': 'Eau',
      'id': 'Air',
      'ms': 'Air',
      'fa': 'آب',
      'so': 'Biyo',
      'ha': 'Ruwa',
      'sw': 'Maji',
    },
    'filter_shade': {
      'ar': 'ظل',
      'en': 'Shade',
      'ur': 'سایہ',
      'bn': 'ছায়া',
      'tr': 'Gölgelik',
      'fr': 'Ombre',
      'id': 'Teduhan',
      'ms': 'Teduhan',
      'fa': 'سایه',
      'so': 'Hooska',
      'ha': 'Inuwa',
      'sw': 'Kivuli',
    },

    // ─── شاشة الملف الطبي ───
    'med_title': {
      'ar': 'الملف الطبي للرعاية',
      'en': 'Medical Care Profile',
      'ur': 'طبی معلومات',
      'bn': 'চিকিৎসা প্রোফাইল',
      'tr': 'Tıbbi Profil',
      'fr': 'Profil Médical',
      'id': 'Profil Medis',
      'ms': 'Profil Perubatan',
      'fa': 'پرونده پزشکی',
      'so': 'Xogta Caafimaadka',
      'ha': 'Bayanin Lafiya',
      'sw': 'Wasifu wa Afya',
    },
    'med_name': {
      'ar': 'الاسم الكامل',
      'en': 'Full Name',
      'ur': 'پورا نام',
      'bn': 'পূর্ণ নাম',
      'tr': 'Adı Soyadı',
      'fr': 'Nom Complet',
      'id': 'Nama Lengkap',
      'ms': 'Nama Penuh',
      'fa': 'نام کامل',
      'so': 'Magaca Buuxa',
      'ha': 'Cikakken Suna',
      'sw': 'Jina Kamili',
    },
    'med_blood': {
      'ar': 'فصيلة الدم',
      'en': 'Blood Type',
      'ur': 'بلڈ گروپ',
      'bn': 'রক্তের গ্রুপ',
      'tr': 'Kan Grubu',
      'fr': 'Groupe Sanguin',
      'id': 'Golongan Darah',
      'ms': 'Kumpulan Darah',
      'fa': 'گروه خونی',
      'so': 'Nooca Dhiigga',
      'ha': 'Nau\'in Jini',
      'sw': 'Kundi la Damu',
    },
    'med_id': {
      'ar': 'الرقم القومي / جواز السفر',
      'en': 'National ID / Passport',
      'ur': 'قومی شناختی کارڈ / پاسپورٹ',
      'bn': 'জাতীয় পরিচয়পত্র / পাসপোর্ট',
      'tr': 'T.C. No / Pasaport',
      'fr': 'N° National / Passeport',
      'id': 'KTP / Paspor',
      'ms': 'No. ID / Pasport',
      'fa': 'کد ملی / گذرنامه',
      'so': 'Aqoonsiga / Baasaboorka',
      'ha': 'ID / Fasfo',
      'sw': 'Kitambulisho / Pasipoti',
    },
    'med_address': {
      'ar': 'عنوان السكن في مكة',
      'en': 'Makkah Residence Address',
      'ur': 'مکہ میں رہائش کا پتہ',
      'bn': 'মক্কার আবাসনের ঠিকানা',
      'tr': 'Mekke Konaklama Adresi',
      'fr': 'Adresse de résidence à La Mecque',
      'id': 'Alamat Tempat Tinggal di Mekkah',
      'ms': 'Alamat Penginapan di Makkah',
      'fa': 'آدرس اقامت در مکه',
      'so': 'Ciwaanka Xaafadda ee Makkah',
      'ha': 'Adireshin Mazauni A Makka',
      'sw': 'Anwani ya Makazi Makkah',
    },
    'med_phone': {
      'ar': 'رقم تواصل للطوارئ',
      'en': 'Emergency Contact Number',
      'ur': 'ہنگامی رابطہ نمبر',
      'bn': 'জরুরী যোগাযোগ নম্বর',
      'tr': 'Acil Durum İletişim Numarası',
      'fr': 'Numéro de Contact d\'Urgence',
      'id': 'Nomor Kontak Darurat',
      'ms': 'Nombor Hubungi Kecemasan',
      'fa': 'شماره تماس اضطراری',
      'so': 'Lambarka Xiriirka Xaaladda Degdegga',
      'ha': 'Lambar Tuntuɓar Gaggawa',
      'sw': 'Nambari ya Mawasiliano ya Dharura',
    },
    'med_chronic': {
      'ar': 'أمراض مزمنة (سكر/ضغط)',
      'en': 'Chronic Diseases (Diabetes/Blood Pressure)',
      'ur': 'دائمہ بیماریاں (ذیابیطس/بلڈ پریشر)',
      'bn': 'দীর্ঘস্থায়ী রোগ (ডায়াবেটিস/রক্তচাপ)',
      'tr': 'Kronik Hastalıklar (Şeker/Tansiyon)',
      'fr': 'Maladies chroniques (Diabète/Tension)',
      'id': 'Penyakit Kronis (Diabetes/Tekanan Darah)',
      'ms': 'Penyakit Kronik (Kencing Manis/Tekanan Darah)',
      'fa': 'بیماری‌های مزمن (دیابت/فشارخون)',
      'so': 'Cudurrada Degdegga (Sonkorow/Cadaadiska Dhiigga)',
      'ha': 'Cututtukan Dogon Zango (Suga/Jini)',
      'sw': 'Magonjwa ya Kudumu (Kisukari/Shinikizo la Damu)',
    },
    'med_notes': {
      'ar': 'ملاحظات هامة للسلامة',
      'en': 'Important Safety Notes',
      'ur': 'اہم حفاظتی نوٹ',
      'bn': 'গুরুত্বপূর্ণ নিরাপত্তা নোট',
      'tr': 'Önemli Güvenlik Notları',
      'fr': 'Notes de Sécurité Importantes',
      'id': 'Catatan Keselamatan Penting',
      'ms': 'Nota Keselamatan Penting',
      'fa': 'یادداشت‌های مهم ایمنی',
      'so': 'Qoraalada Muhiimka ah ee Amniga',
      'ha': 'Mahimman Bayanan Aminci',
      'sw': 'Maelezo Muhimu ya Usalama',
    },
    'save_btn': {
      'ar': 'حفظ التغييرات',
      'en': 'Save Changes',
      'ur': 'تبدیلیاں محفوظ کریں',
      'bn': 'পরিবর্তন সংরক্ষণ করুন',
      'tr': 'Değişiklikleri Kaydet',
      'fr': 'Enregistrer les modifications',
      'id': 'Simpan Perubahan',
      'ms': 'Simpan Perubahan',
      'fa': 'ذخیره تغییرات',
      'so': 'Keydi Beddelaadaha',
      'ha': 'Ajiye Canje-Canje',
      'sw': 'Hifadhi Mabadiliko',
    },
    'save_success': {
      'ar': 'تم حفظ البيانات بنجاح',
      'en': 'Data saved successfully',
      'ur': 'معلومات کامیابی سے محفوظ ہو گئیں',
      'bn': 'তথ্য সফলভাবে সংরক্ষিত হয়েছে',
      'tr': 'Bilgiler başarıyla kaydedildi',
      'fr': 'Données enregistrées avec succès',
      'id': 'Data berhasil disimpan',
      'ms': 'Data berjaya disimpan',
      'fa': 'داده‌ها با موفقیت ذخیره شد',
      'so': 'Xogta si guul leh ayaa loo keydiyay',
      'ha': 'An ajiye bayanan cikin nasara',
      'sw': 'Data imehifadhiwa kwa mafanikio',
    },

    // ─── تبويب الطواف والسعي ───
    'btn_tawaf': {
      'ar': 'طواف 🕋',
      'en': 'Tawaf 🕋',
      'ur': 'طواف 🕋',
      'bn': 'তওয়াফ 🕋',
      'tr': 'Tavaf 🕋',
      'fr': 'Tawaf 🕋',
      'id': 'Tawaf 🕋',
      'ms': 'Tawaf 🕋',
      'fa': 'طواف 🕋',
      'so': 'Daawaf 🕋',
      'ha': 'Tawafi 🕋',
      'sw': 'Tawaf 🕋',
    },
    'btn_sai': {
      'ar': 'سعي ⛰️',
      'en': 'Sa\'ee ⛰️',
      'ur': 'سعی ⛰️',
      'bn': 'সাঈ ⛰️',
      'tr': 'Sa\'y ⛰️',
      'fr': 'Sa\'ee ⛰️',
      'id': 'Sa\'i ⛰️',
      'ms': 'Sa\'ie ⛰️',
      'fa': 'سعی ⛰️',
      'so': 'Sa\'yiga ⛰️',
      'ha': 'Sa\'ayi ⛰️',
      'sw': 'Sa\'i ⛰️',
    },
    'calc_method': {
      'ar': 'كيفية الحساب:',
      'en': 'Calculation Method:',
      'ur': 'حساب کا طریقہ:',
      'bn': 'গণনার পদ্ধতি:',
      'tr': 'Sayma Yöntemi:',
      'fr': 'Méthode de calcul :',
      'id': 'Metode Perhitungan:',
      'ms': 'Kaedah Pengiraan:',
      'fa': 'روش محاسبه:',
      'so': 'Habka Xisaabinta:',
      'ha': 'Hanyar Kirga:',
      'sw': 'Njia ya Kuhesabu:',
    },
    'auto_counter': {
      'ar': 'عداد آلي 🤖',
      'en': 'Auto Counter 🤖',
      'ur': 'خودکار عداد 🤖',
      'bn': 'স্বয়ংক্রিয় কাউন্টার 🤖',
      'tr': 'Otomatik Sayaç 🤖',
      'fr': 'Compteur automatique 🤖',
      'id': 'Penghitung Otomatis 🤖',
      'ms': 'Pembilang Auto 🤖',
      'fa': 'شمارنده خودکار 🤖',
      'so': 'Tiriyaha Tooska ah 🤖',
      'ha': 'Kirga Atomatik 🤖',
      'sw': 'Kihesabu cha Kiotomatiki 🤖',
    },
    'manual_counter': {
      'ar': 'مرئي يدوي 📋',
      'en': 'Manual 📋',
      'ur': 'دستی 📋',
      'bn': 'ম্যানুয়াল 📋',
      'tr': 'Manuel 📋',
      'fr': 'Manuel 📋',
      'id': 'Manual 📋',
      'ms': 'Manual 📋',
      'fa': 'دستی 📋',
      'so': 'Gacanta 📋',
      'ha': 'Hannu 📋',
      'sw': 'Mwenyewe 📋',
    },
    'auto_sai_title': {
      'ar': 'عداد أشواط السعي التلقائي',
      'en': 'Automatic Sa\'ee Counter',
      'ur': 'سعی کا خودکار عداد',
      'bn': 'স্বয়ংক্রিয় সাঈ কাউন্টার',
      'tr': 'Otomatik Sa\'y Sayacı',
      'fr': 'Compteur automatique de Sa\'ee',
      'id': 'Penghitung Sa\'i Otomatis',
      'ms': 'Pembilang Sa\'ie Automatik',
      'fa': 'شمارنده خودکار سعی',
      'so': 'Tiriyaha Tooska ah ee Sa\'yiga',
      'ha': 'Kirga Atomatik na Sa\'ayi',
      'sw': 'Kihesabu cha Kiotomatiki cha Sa\'i',
    },
    'auto_tawaf_title': {
      'ar': 'عداد أشواط الطواف التلقائي',
      'en': 'Automatic Tawaf Counter',
      'ur': 'طواف کا خودکار عداد',
      'bn': 'স্বয়ংক্রিয় তওয়াফ কাউন্টার',
      'tr': 'Otomatik Tavaf Sayacı',
      'fr': 'Compteur automatique de Tawaf',
      'id': 'Penghitung Tawaf Otomatis',
      'ms': 'Pembilang Tawaf Automatik',
      'fa': 'شمارنده خودکار طواف',
      'so': 'Tiriyaha Tooska ah ee Daawafka',
      'ha': 'Kirga Atomatik na Tawafi',
      'sw': 'Kihesabu cha Kiotomatiki cha Tawaf',
    },
    'shawt_word': {
      'ar': 'شوط',
      'en': 'Round',
      'ur': 'چکر',
      'bn': 'রাউন্ড',
      'tr': 'Tur',
      'fr': 'Tour',
      'id': 'Putaran',
      'ms': 'Pusingan',
      'fa': 'دور',
      'so': 'Wareeg',
      'ha': 'Zagaye',
      'sw': 'Raundi',
    },
    'congrats_msg': {
      'ar': '🎉 تقبّل الله منك!',
      'en': '🎉 May Allah accept it from you!',
      'ur': '🎉 اللہ آپ سے قبول فرمائے!',
      'bn': '🎉 আল্লাহ আপনার কাছ থেকে কবুল করুন!',
      'tr': '🎉 Allah senden kabul etsin!',
      'fr': '🎉 Qu\'Allah accepte de toi !',
      'id': '🎉 Semoga Allah menerimanya dari Anda!',
      'ms': '🎉 Semoga Allah menerima daripadamu!',
      'fa': '🎉 قبول حق تعالی!',
      'so': '🎉 Eebe ha ka qaato!',
      'ha': '🎉 Allah ya karɓa daga gare ka!',
      'sw': '🎉 Allah akikubalie kutoka kwako!',
    },
    'steps_label': {
      'ar': 'الخطوات: ',
      'en': 'Steps: ',
      'ur': 'قدم: ',
      'bn': 'পদক্ষেপ: ',
      'tr': 'Adımlar: ',
      'fr': 'Pas : ',
      'id': 'Langkah: ',
      'ms': 'Langkah: ',
      'fa': 'قدم‌ها: ',
      'so': 'Tallaabada: ',
      'ha': 'Mataki: ',
      'sw': 'Hatua: ',
    },
    'dir_safa_marwa': {
      'ar': '⬅️ متجه من الصفا إلى المروة',
      'en': '⬅️ Safa to Marwah',
      'ur': '⬅️ صفا سے مروہ کی طرف',
      'bn': '⬅️ সাফা থেকে মারওয়া',
      'tr': '⬅️ Safa\'dan Merve\'ye',
      'fr': '⬅️ De Safa à Marwah',
      'id': '⬅️ Dari Safa ke Marwah',
      'ms': '⬅️ Dari Safa ke Marwah',
      'fa': '⬅️ از صفا به مروه',
      'so': '⬅️ Safa ilaa Marwah',
      'ha': '⬅️ Daga Safa zuwa Marwa',
      'sw': '⬅️ Kutoka Safa hadi Marwah',
    },
    'dir_marwa_safa': {
      'ar': '➡️ متجه من المروة إلى الصفا',
      'en': '➡️ Marwah to Safa',
      'ur': '➡️ مروہ سے صفا کی طرف',
      'bn': '➡️ মারওয়া থেকে সাফা',
      'tr': '➡️ Merve\'den Safa\'ya',
      'fr': '➡️ De Marwah à Safa',
      'id': '➡️ Dari Marwah ke Safa',
      'ms': '➡️ Dari Marwah ke Safa',
      'fa': '➡️ از مروه به صفا',
      'so': '➡️ Marwah ilaa Safa',
      'ha': '➡️ Daga Marwa zuwa Safa',
      'sw': '➡️ Kutoka Marwah hadi Safa',
    },
    'record_shawt': {
      'ar': 'تسجيل شوط',
      'en': 'Record Round',
      'ur': 'چکر درج کریں',
      'bn': 'রাউন্ড রেকর্ড করুন',
      'tr': 'Tur Kaydet',
      'fr': 'Enregistrer le tour',
      'id': 'Catat Putaran',
      'ms': 'Rekod Pusingan',
      'fa': 'ثبت دور',
      'so': 'Diiwaangeli Wareeg',
      'ha': 'Yi Rikodin Zagaye',
      'sw': 'Rekodi Raundi',
    },
    'reset_btn': {
      'ar': 'إعادة ضبط',
      'en': 'Reset',
      'ur': 'دوبارہ شروع',
      'bn': 'রিসেট',
      'tr': 'Sıfırla',
      'fr': 'Réinitialiser',
      'id': 'Reset',
      'ms': 'Set Semula',
      'fa': 'بازنشانی',
      'so': 'Dib u Dejin',
      'ha': 'Sake Saiti',
      'sw': 'Weka Upya',
    },
    'duaa_shawt': {
      'ar': 'دعاء الشوط',
      'en': 'Du\'aa for Round',
      'ur': 'چکر کی دعا',
      'bn': 'রাউন্ডের দোয়া',
      'tr': 'Tur Duası',
      'fr': 'Du\'aa du tour',
      'id': 'Doa Putaran',
      'ms': 'Doa Pusingan',
      'fa': 'دعای دور',
      'so': 'Ducada Wareegga',
      'ha': 'Addu\'ar Zagaye',
      'sw': 'Dua ya Raundi',
    },
    'audio_stopped_note': {
      'ar': 'تم إيقاف التلاوة الصوتية الآلية للدعاء ليتسنى لك مناجاة الله براحة.',
      'en': 'Automatic audio for Du\'aa is muted so you can converse with Allah comfortably.',
      'ur': 'دعا کی آواز خاموش کر دی گئی تاکہ آپ اللہ سے سکون سے مناجات کر سکیں۔',
      'bn': 'দোয়ার স্বয়ংক্রিয় অডিও নিরব করা হয়েছে যাতে আপনি আল্লাহর সাথে শান্তিতে কথা বলতে পারেন।',
      'tr': 'Duanın otomatik sesi kapatıldı, böylece Allah ile rahatça konuşabilirsiniz.',
      'fr': 'L\'audio automatique du Du\'aa est coupé pour vous permettre de converser avec Allah sereinement.',
      'id': 'Audio otomatis untuk Doa dimatikan agar Anda dapat berbicara dengan Allah dengan nyaman.',
      'ms': 'Audio automatik untuk Doa dimatikan supaya anda boleh bercakap dengan Allah dengan selesa.',
      'fa': 'صدای خودکار دعا قطع شده تا بتوانید با آرامش با خداوند مناجات کنید.',
      'so': 'Dhawaaqa tooska ah ee Ducada waxa la damiyay si aad uga hadli karto Ilaahay nabad.',
      'ha': 'An kashe sauti na atomatik na addu\'a don ku iya yin magana da Allah cikin natsuwa.',
      'sw': 'Sauti ya kiotomatiki ya Dua imenyamazishwa ili uweze kuzungumza na Allah kwa utulivu.',
    },
    'reset_all_btn': {
      'ar': 'إعادة ضبط جميع الأشواط',
      'en': 'Reset All Rounds',
      'ur': 'تمام چکر دوبارہ شروع کریں',
      'bn': 'সব রাউন্ড রিসেট করুন',
      'tr': 'Tüm Turları Sıfırla',
      'fr': 'Réinitialiser tous les tours',
      'id': 'Reset Semua Putaran',
      'ms': 'Set Semula Semua Pusingan',
      'fa': 'بازنشانی همه دورها',
      'so': 'Dib u Deji Dhammaan Wareegyada',
      'ha': 'Sake Saiti Dukkan Zagayen',
      'sw': 'Weka Upya Raundi Zote',
    },
    'shawt_prefix': {
      'ar': 'الشوط',
      'en': 'Round',
      'ur': 'چکر',
      'bn': 'রাউন্ড',
      'tr': 'Tur',
      'fr': 'Tour',
      'id': 'Putaran',
      'ms': 'Pusingan',
      'fa': 'دور',
      'so': 'Wareeg',
      'ha': 'Zagaye',
      'sw': 'Raundi',
    },
    'safa_to_marwa': {
      'ar': 'من الصفا إلى المروة',
      'en': 'Safa to Marwah',
      'ur': 'صفا سے مروہ',
      'bn': 'সাফা থেকে মারওয়া',
      'tr': 'Safa\'dan Merve\'ye',
      'fr': 'De Safa à Marwah',
      'id': 'Dari Safa ke Marwah',
      'ms': 'Safa ke Marwah',
      'fa': 'از صفا به مروه',
      'so': 'Safa ilaa Marwah',
      'ha': 'Daga Safa zuwa Marwa',
      'sw': 'Kutoka Safa hadi Marwah',
    },
    'marwa_to_safa': {
      'ar': 'من المروة إلى الصفا',
      'en': 'Marwah to Safa',
      'ur': 'مروہ سے صفا',
      'bn': 'মারওয়া থেকে সাফা',
      'tr': 'Merve\'den Safa\'ya',
      'fr': 'De Marwah à Safa',
      'id': 'Dari Marwah ke Safa',
      'ms': 'Marwah ke Safa',
      'fa': 'از مروه به صفا',
      'so': 'Marwah ilaa Safa',
      'ha': 'Daga Marwa zuwa Safa',
      'sw': 'Kutoka Marwah hadi Safa',
    },

    // ─── حوار إعادة الضبط ───
    'reset_dialog_title': {
      'ar': 'إعادة ضبط العداد',
      'en': 'Reset Counter',
      'ur': 'عداد دوبارہ ترتیب دیں',
      'bn': 'কাউন্টার রিসেট করুন',
      'tr': 'Sayacı Sıfırla',
      'fr': 'Réinitialiser le compteur',
      'id': 'Reset Penghitung',
      'ms': 'Set Semula Pembilang',
      'fa': 'بازنشانی شمارنده',
      'so': 'Dib u Deji Tiriyaha',
      'ha': 'Sake Saiti Kirga',
      'sw': 'Weka Upya Kihesabu',
    },
    'reset_dialog_msg': {
      'ar': 'هل أنت متأكد من إعادة ضبط العداد من البداية؟',
      'en': 'Are you sure you want to reset the counter from the beginning?',
      'ur': 'کیا آپ واقعی عداد دوبارہ شروع سے ترتیب دینا چاہتے ہیں؟',
      'bn': 'আপনি কি শুরু থেকে কাউন্টার রিসেট করতে নিশ্চিত?',
      'tr': 'Sayacı baştan sıfırlamak istediğinizden emin misiniz?',
      'fr': 'Voulez-vous vraiment réinitialiser le compteur depuis le début ?',
      'id': 'Apakah Anda yakin ingin mereset penghitung dari awal?',
      'ms': 'Adakah anda pasti ingin menetapkan semula pembilang dari awal?',
      'fa': 'آیا مطمئن هستید که می‌خواهید شمارنده را از ابتدا بازنشانی کنید؟',
      'so': 'Ma hubtaa inaad dib u dejiso tiriyaha bilowga?',
      'ha': 'Shin kun tabbata kuna son sake saitin kirga daga farko?',
      'sw': 'Je, una uhakika unataka kuweka upya kihesabu kutoka mwanzo?',
    },
    'cancel_btn': {
      'ar': 'إلغاء',
      'en': 'Cancel',
      'ur': 'منسوخ کریں',
      'bn': 'বাতিল করুন',
      'tr': 'İptal',
      'fr': 'Annuler',
      'id': 'Batal',
      'ms': 'Batal',
      'fa': 'لغو',
      'so': 'Jooji',
      'ha': 'Soke',
      'sw': 'Ghairi',
    },
    'confirm_reset': {
      'ar': 'نعم، إعادة ضبط',
      'en': 'Yes, Reset',
      'ur': 'ہاں، دوبارہ شروع کریں',
      'bn': 'হ্যাঁ, রিসেট করুন',
      'tr': 'Evet, Sıfırla',
      'fr': 'Oui, réinitialiser',
      'id': 'Ya, Reset',
      'ms': 'Ya, Set Semula',
      'fa': 'بله، بازنشانی کن',
      'so': 'Haa, Dib u Deji',
      'ha': 'I-i, Sake Saiti',
      'sw': 'Ndiyo, Weka Upya',
    },

    // ─── محاكاة الخريطة والموقع ───
    'loc_real': {
      'ar': 'GPS حقيقي 📍',
      'en': 'Real GPS 📍',
      'ur': 'اصل GPS 📍',
      'bn': 'আসল GPS 📍',
      'tr': 'Gerçek GPS 📍',
      'fr': 'GPS Réel 📍',
      'id': 'GPS Nyata 📍',
      'ms': 'GPS Sebenar 📍',
      'fa': 'GPS واقعی 📍',
      'so': 'GPS Xaqiiqa ah 📍',
      'ha': 'GPS na Gaske 📍',
      'sw': 'GPS Halisi 📍',
    },
    'loc_makkah': {
      'ar': 'محاكاة مكة 🕋',
      'en': 'Makkah Simul 🕋',
      'ur': 'مکہ نقلی 🕋',
      'bn': 'মক্কা সিমুলেশন 🕋',
      'tr': 'Mekke Sim 🕋',
      'fr': 'Simul. La Mecque 🕋',
      'id': 'Simulasi Mekkah 🕋',
      'ms': 'Simulasi Makkah 🕋',
      'fa': 'شبیه‌سازی مکه 🕋',
      'so': 'Muuqaalka Makkah 🕋',
      'ha': 'Kwaikwayon Makka 🕋',
      'sw': 'Uigaji wa Makkah 🕋',
    },
    'loc_picked': {
      'ar': 'النقطة المحددة 🎯',
      'en': 'Picked Spot 🎯',
      'ur': 'منتخب مقام 🎯',
      'bn': 'নির্বাচিত স্থান 🎯',
      'tr': 'Seçilen Nokta 🎯',
      'fr': 'Point Sélectionné 🎯',
      'id': 'Titik Dipilih 🎯',
      'ms': 'Titik Dipilih 🎯',
      'fa': 'نقطه انتخابی 🎯',
      'so': 'Goobta La Doortay 🎯',
      'ha': 'Wurin Da Aka Zaba 🎯',
      'sw': 'Mahali Paliochaguliwa 🎯',
    },
    'pick_map_prompt': {
      'ar': 'اضغط على الخريطة لتحديد موقعك الوهمي.',
      'en': 'Tap on the map to set your mocked location.',
      'ur': 'اپنا نقلی مقام متعین کرنے کے لیے نقشے پر ٹیپ کریں۔',
      'bn': 'আপনার নকল অবস্থান নির্ধারণ করতে মানচিত্রে ট্যাপ করুন।',
      'tr': 'Sahte konumunuzu ayarlamak için haritaya dokunun.',
      'fr': 'Appuyez sur la carte pour définir votre position simulée.',
      'id': 'Ketuk peta untuk mengatur lokasi tiruan Anda.',
      'ms': 'Ketik peta untuk tetapkan lokasi palsu anda.',
      'fa': 'برای تنظیم موقعیت مصنوعی روی نقشه ضربه بزنید.',
      'so': 'Ku dhufo khariidadda si aad u dejiso goobta khiyaalka ah.',
      'ha': 'Danna taswira don saita wurinka na kwaikwayo.',
      'sw': 'Gusa ramani kuweka mahali pako pa kuigwa.',
    },
    'service_points': {
      'ar': 'نقاط الخدمة',
      'en': 'Service Points',
      'ur': 'خدمت مراکز',
      'bn': 'সেবা কেন্দ্র',
      'tr': 'Hizmet Noktaları',
      'fr': 'Points de Service',
      'id': 'Titik Layanan',
      'ms': 'Titik Perkhidmatan',
      'fa': 'نقاط خدمات',
      'so': 'Meelaha Adeegga',
      'ha': 'Wuraren Sabis',
      'sw': 'Vituo vya Huduma',
    },

    // ─── خريطة مكة الأوفلاين ───
    'offline_map_title_makkah': {
      'ar': 'خريطة مكة الأوفلاين',
      'en': 'Makkah Offline Map',
      'ur': 'مکہ کا آف لائن نقشہ',
      'bn': 'মক্কার অফলাইন মানচিত্র',
      'tr': 'Mekke Çevrimdışı Haritası',
      'fr': 'Carte hors ligne de La Mecque',
      'id': 'Peta Offline Mekkah',
      'ms': 'Peta Luar Talian Makkah',
      'fa': 'نقشه آفلاین مکه',
      'so': 'Khariidadda Offline ee Makkah',
      'ha': 'Taswirar Makka Offline',
      'sw': 'Ramani ya Makkah Isiyohitaji Mtandao',
    },
    'offline_map_title_sim': {
      'ar': 'محاكي المسار الآمن',
      'en': 'Safe Route Simulator',
      'ur': 'محفوظ راستے کا محاکی',
      'bn': 'নিরাপদ রুট সিমুলেটর',
      'tr': 'Güvenli Rota Simülatörü',
      'fr': 'Simulateur d\'itinéraire sûr',
      'id': 'Simulator Rute Aman',
      'ms': 'Simulator Laluan Selamat',
      'fa': 'شبیه‌ساز مسیر ایمن',
      'so': 'Muuqaalaha Wadada Amaan',
      'ha': 'Mai Kwaikwayon Hanyar Aminci',
      'sw': 'Kisimulia cha Njia Salama',
    },
    'map_loading_init': {
      'ar': 'جاري تهيئة الخريطة الأوفلاين...',
      'en': 'Initializing offline map...',
      'ur': 'آف لائن نقشہ تیار ہو رہا ہے...',
      'bn': 'অফলাইন মানচিত্র শুরু হচ্ছে...',
      'tr': 'Çevrimdışı harita başlatılıyor...',
      'fr': 'Initialisation de la carte hors ligne...',
      'id': 'Menginisialisasi peta offline...',
      'ms': 'Memulakan peta luar talian...',
      'fa': 'در حال راه‌اندازی نقشه آفلاین...',
      'so': 'Bilowga khariidadda offline...',
      'ha': 'Ana fara taswira offline...',
      'sw': 'Inaanzisha ramani ya nje ya mtandao...',
    },
    'map_loading_file': {
      'ar': 'جاري تحضير ملف الخريطة...',
      'en': 'Preparing map file...',
      'ur': 'نقشے کی فائل تیار ہو رہی ہے...',
      'bn': 'মানচিত্র ফাইল প্রস্তুত হচ্ছে...',
      'tr': 'Harita dosyası hazırlanıyor...',
      'fr': 'Préparation du fichier de carte...',
      'id': 'Menyiapkan file peta...',
      'ms': 'Menyediakan fail peta...',
      'fa': 'در حال آماده‌سازی فایل نقشه...',
      'so': 'Diyaarinta faylka khariidadda...',
      'ha': 'Ana shirya fayil ɗin taswira...',
      'sw': 'Inaandaa faili la ramani...',
    },
    'map_loading_copy': {
      'ar': 'جاري نسخ بيانات الخريطة...',
      'en': 'Copying map data...',
      'ur': 'نقشے کا ڈیٹا کاپی ہو رہا ہے...',
      'bn': 'মানচিত্রের তথ্য কপি হচ্ছে...',
      'tr': 'Harita verisi kopyalanıyor...',
      'fr': 'Copie des données de la carte...',
      'id': 'Menyalin data peta...',
      'ms': 'Menyalin data peta...',
      'fa': 'در حال کپی داده‌های نقشه...',
      'so': 'Koobiyaynta xogta khariidadda...',
      'ha': 'Ana kwafin bayanin taswira...',
      'sw': 'Ina nakili data ya ramani...',
    },
    'map_loading_engine': {
      'ar': 'جاري تهيئة محرك الخريطة...',
      'en': 'Initializing map engine...',
      'ur': 'نقشے کا انجن تیار ہو رہا ہے...',
      'bn': 'মানচিত্র ইঞ্জিন শুরু হচ্ছে...',
      'tr': 'Harita motoru başlatılıyor...',
      'fr': 'Initialisation du moteur de carte...',
      'id': 'Menginisialisasi mesin peta...',
      'ms': 'Memulakan enjin peta...',
      'fa': 'در حال راه‌اندازی موتور نقشه...',
      'so': 'Bilowga injinka khariidadda...',
      'ha': 'Ana fara injin taswira...',
      'sw': 'Inaanzisha injini ya ramani...',
    },
    'map_retry': {
      'ar': 'إعادة المحاولة',
      'en': 'Retry',
      'ur': 'دوبارہ کوشش کریں',
      'bn': 'আবার চেষ্টা করুন',
      'tr': 'Tekrar Dene',
      'fr': 'Réessayer',
      'id': 'Coba Lagi',
      'ms': 'Cuba Semula',
      'fa': 'تلاش مجدد',
      'so': 'Isku day Mar Kale',
      'ha': 'Sake Gwadawa',
      'sw': 'Jaribu Tena',
    },
    'map_voice_tooltip': {
      'ar': 'إرشاد صوتي للمسار',
      'en': 'Voice route guidance',
      'ur': 'آواز سے راستہ رہنمائی',
      'bn': 'ভয়েস রুট গাইডেন্স',
      'tr': 'Sesli rota yönlendirmesi',
      'fr': 'Guidage vocal de l\'itinéraire',
      'id': 'Panduan rute suara',
      'ms': 'Panduan laluan suara',
      'fa': 'راهنمایی مسیر صوتی',
      'so': 'Hagahaynta codka ee wadada',
      'ha': 'Jagorar hanyar murya',
      'sw': 'Mwongozo wa njia kwa sauti',
    },
    'map_card_title': {
      'ar': 'خريطة مكة المكرمة الأوفلاين',
      'en': 'Makkah Offline Map',
      'ur': 'مکہ المکرمہ کا آف لائن نقشہ',
      'bn': 'মক্কা মুকাররমার অফলাইন মানচিত্র',
      'tr': 'Mekke Çevrimdışı Haritası',
      'fr': 'Carte hors ligne de La Mecque',
      'id': 'Peta Offline Mekkah',
      'ms': 'Peta Luar Talian Makkah Al-Mukarramah',
      'fa': 'نقشه آفلاین مکه مکرمه',
      'so': 'Khariidadda Offline ee Makkah Al-Mukarramah',
      'ha': 'Taswirar Makka Al-Mukarrama Offline',
      'sw': 'Ramani ya Makkah Al-Mukarramah Isiyohitaji Mtandao',
    },
    'map_card_subtitle': {
      'ar': 'خريطة تفاعلية كاملة بدون إنترنت\nتشمل المسجد الحرام ومحيطه',
      'en': 'Full interactive map without internet\nCovers Al-Masjid Al-Haram and surroundings',
      'ur': 'بغیر انٹرنیٹ مکمل انٹرایکٹو نقشہ\nمسجد الحرام اور آس پاس کا علاقہ شامل ہے',
      'bn': 'ইন্টারনেট ছাড়া সম্পূর্ণ ইন্টারেক্টিভ মানচিত্র\nমসজিদুল হারাম ও পার্শ্ববর্তী এলাকা অন্তর্ভুক্ত',
      'tr': 'İnternetsiz tam interaktif harita\nMescid-i Haram ve çevresini kapsar',
      'fr': 'Carte interactive complète sans internet\nCouvre la Grande Mosquée et ses alentours',
      'id': 'Peta interaktif lengkap tanpa internet\nMencakup Masjidil Haram dan sekitarnya',
      'ms': 'Peta interaktif lengkap tanpa internet\nMerangkumi Masjidil Haram dan kawasan sekitarnya',
      'fa': 'نقشه تعاملی کامل بدون اینترنت\nشامل مسجدالحرام و اطراف آن',
      'so': 'Khariidad buuxda oo xidid la\'aanta xidid\nWaxay qabataa Masjidul Xaraam iyo agagaarka',
      'ha': 'Taswira cikakke mai hulɗa ba tare da intanet ba\nTana ɗaukar Masallaci Al-Haram da kewaye',
      'sw': 'Ramani kamili inayoshirikiana bila mtandao\nInajumuisha Msikiti Al-Haram na mazingira yake',
    },
    'open_map_btn': {
      'ar': 'افتح الخريطة',
      'en': 'Open Map',
      'ur': 'نقشہ کھولیں',
      'bn': 'মানচিত্র খুলুন',
      'tr': 'Haritayı Aç',
      'fr': 'Ouvrir la carte',
      'id': 'Buka Peta',
      'ms': 'Buka Peta',
      'fa': 'باز کردن نقشه',
      'so': 'Fur Khariidadda',
      'ha': 'Buɗe Taswira',
      'sw': 'Fungua Ramani',
    },
    'read_aloud_tooltip': {
      'ar': 'قراءة صوتية',
      'en': 'Read aloud',
      'ur': 'اونچی آواز سے پڑھیں',
      'bn': 'জোরে পড়ুন',
      'tr': 'Sesli okuma',
      'fr': 'Lecture à voix haute',
      'id': 'Baca keras',
      'ms': 'Baca kuat',
      'fa': 'خواندن با صدای بلند',
      'so': 'Kor u akhriso',
      'ha': 'Karanta da babbar murya',
      'sw': 'Soma kwa sauti',
    },

    // ─── تبويب الطوارئ ───
    'ble_network_title': {
      'ar': 'شبكة سَكينة للطوارئ',
      'en': 'Sakeenah Emergency Network',
      'ur': 'سکینہ ہنگامی نیٹ ورک',
      'bn': 'সাকিনাহ জরুরী নেটওয়ার্ক',
      'tr': 'Sakeenah Acil Ağı',
      'fr': 'Réseau d\'urgence Sakeenah',
      'id': 'Jaringan Darurat Sakeenah',
      'ms': 'Rangkaian Kecemasan Sakeenah',
      'fa': 'شبکه اورژانسی سکینه',
      'so': 'Shabakadda Xaaladda Degdegga ee Sakeenah',
      'ha': 'Hanyar Gaggawa ta Sakeenah',
      'sw': 'Mtandao wa Dharura wa Sakeenah',
    },
    'ble_peers_connected': {
      'ar': ' حجاج بالقرب منك متصلون',
      'en': ' pilgrims nearby connected',
      'ur': ' قریبی حجاج متصل ہیں',
      'bn': ' কাছের হাজী সংযুক্ত',
      'tr': ' yakın hacı bağlı',
      'fr': ' pèlerins proches connectés',
      'id': ' jemaah terdekat terhubung',
      'ms': ' jemaah berdekatan tersambung',
      'fa': ' حاجی نزدیک متصل شده',
      'so': ' xujayaal u dhow xidnaanaya',
      'ha': ' mahajjata kusa suna haɗe',
      'sw': ' mahujaji wa karibu wameunganishwa',
    },
    'ble_enable_prompt': {
      'ar': 'يرجى تفعيل البلوتوث لاكتشاف الحجاج',
      'en': 'Please enable Bluetooth to discover pilgrims',
      'ur': 'حجاج کو دریافت کرنے کے لیے بلوٹوتھ فعال کریں',
      'bn': 'হাজীদের খুঁজে পেতে ব্লুটুথ চালু করুন',
      'tr': 'Hacıları bulmak için Bluetooth\'u etkinleştirin',
      'fr': 'Veuillez activer le Bluetooth pour découvrir les pèlerins',
      'id': 'Aktifkan Bluetooth untuk menemukan jemaah',
      'ms': 'Sila aktifkan Bluetooth untuk mengesan jemaah',
      'fa': 'لطفاً بلوتوث را برای پیدا کردن حجاج فعال کنید',
      'so': 'Fadlan fur Bluetooth si aad u hesho xujayaasha',
      'ha': 'Don Allah kunna Bluetooth don gano mahajjata',
      'sw': 'Tafadhali wezesha Bluetooth ili kupata mahujaji',
    },
    'sos_sent_label': {
      'ar': 'تم إرسال نداء الطوارئ!',
      'en': 'Emergency SOS Sent!',
      'ur': 'ہنگامی SOS بھیجا گیا!',
      'bn': 'জরুরী SOS পাঠানো হয়েছে!',
      'tr': 'Acil SOS Gönderildi!',
      'fr': 'SOS d\'urgence envoyé !',
      'id': 'SOS Darurat Terkirim!',
      'ms': 'SOS Kecemasan Dihantar!',
      'fa': 'SOS اورژانسی ارسال شد!',
      'so': 'SOS Xaaladda Degdegga La Diray!',
      'ha': 'An Aika SOS na Gaggawa!',
      'sw': 'SOS ya Dharura Imetumwa!',
    },
    'sos_hold_prompt': {
      'ar': 'اضغط مطوّلاً لإرسال نداء طوارئ',
      'en': 'Hold to Send Emergency SOS',
      'ur': 'ہنگامی SOS بھیجنے کے لیے دبائے رکھیں',
      'bn': 'জরুরী SOS পাঠাতে চেপে ধরুন',
      'tr': 'Acil SOS Göndermek İçin Basılı Tutun',
      'fr': 'Maintenez appuyé pour envoyer un SOS',
      'id': 'Tahan untuk Kirim SOS Darurat',
      'ms': 'Tahan untuk Hantar SOS Kecemasan',
      'fa': 'نگه دارید تا SOS اورژانسی ارسال شود',
      'so': 'Hayso si aad u dirto SOS Xaaladda Degdegga',
      'ha': 'Riƙe don Aika SOS na Gaggawa',
      'sw': 'Shika ili Kutuma SOS ya Dharura',
    },
    'sos_sent_short': {
      'ar': 'تم الإرسال',
      'en': 'Sent',
      'ur': 'بھیجا گیا',
      'bn': 'পাঠানো হয়েছে',
      'tr': 'Gönderildi',
      'fr': 'Envoyé',
      'id': 'Terkirim',
      'ms': 'Dihantar',
      'fa': 'ارسال شد',
      'so': 'La diray',
      'ha': 'An aika',
      'sw': 'Imetumwa',
    },
    'sos_cancel_btn': {
      'ar': 'إلغاء النداء',
      'en': 'Cancel SOS',
      'ur': 'SOS منسوخ کریں',
      'bn': 'SOS বাতিল করুন',
      'tr': 'SOS\'u İptal Et',
      'fr': 'Annuler le SOS',
      'id': 'Batalkan SOS',
      'ms': 'Batal SOS',
      'fa': 'لغو SOS',
      'so': 'Jooji SOS',
      'ha': 'Soke SOS',
      'sw': 'Ghairi SOS',
    },
    'sos_holding': {
      'ar': 'استمر بالضغط...',
      'en': 'Keep pressing...',
      'ur': 'دباتے رہیں...',
      'bn': 'চেপে থাকুন...',
      'tr': 'Basmaya devam edin...',
      'fr': 'Continuez d\'appuyer...',
      'id': 'Terus tekan...',
      'ms': 'Teruskan menekan...',
      'fa': 'به فشار دادن ادامه دهید...',
      'so': 'Sii riix...',
      'ha': 'Ci gaba da danna...',
      'sw': 'Endelea kushika...',
    },
    'sos_notifying': {
      'ar': 'جاري إبلاغ الحجاج القريبين',
      'en': 'Notifying nearby pilgrims',
      'ur': 'قریبی حجاج کو اطلاع دی جا رہی ہے',
      'bn': 'কাছের হাজীদের জানানো হচ্ছে',
      'tr': 'Yakındaki hacılar bilgilendiriliyor',
      'fr': 'Notification des pèlerins proches',
      'id': 'Memberi tahu jemaah terdekat',
      'ms': 'Memberitahu jemaah berdekatan',
      'fa': 'در حال اطلاع‌رسانی به حجاج نزدیک',
      'so': 'Xujayaasha u dhow ayaa la ogeysiinayaa',
      'ha': 'Ana sanar da mahajjata da ke kusa',
      'sw': 'Inawaarifu mahujaji wa karibu',
    },
    'sos_hold_seconds': {
      'ar': 'اضغط مطوّلاً لمدة ثانيتين',
      'en': 'Hold for 2 seconds',
      'ur': '2 سیکنڈ کے لیے دبائے رکھیں',
      'bn': '2 সেকেন্ড চেপে ধরুন',
      'tr': '2 saniye basılı tutun',
      'fr': 'Maintenez appuyé pendant 2 secondes',
      'id': 'Tahan selama 2 detik',
      'ms': 'Tahan selama 2 saat',
      'fa': '2 ثانیه نگه دارید',
      'so': 'U hayso 2 ilbiriqsi',
      'ha': 'Riƙe na daƙiƙa 2',
      'sw': 'Shika kwa sekunde 2',
    },
    // Nearby pilgrims section
    'nearby_pilgrims': {
      'ar': 'حجاج قريبون',
      'en': 'Nearby Pilgrims',
      'ur': 'قریبی حجاج',
      'bn': 'কাছের হাজীগণ',
      'tr': 'Yakındaki Hacılar',
      'fr': 'Pèlerins à proximité',
      'id': 'Jemaah Terdekat',
      'ms': 'Jemaah Berdekatan',
      'fa': 'حجاج نزدیک',
      'so': 'Xujayaasha Ku Dhow',
      'ha': 'Mahajjata Kusa',
      'sw': 'Mahujaji wa Karibu',
    },
    'signal_strength': {
      'ar': 'الإشارة: ',
      'en': 'Signal: ',
      'ur': 'سگنل: ',
      'bn': 'সংকেত: ',
      'tr': 'Sinyal: ',
      'fr': 'Signal : ',
      'id': 'Sinyal: ',
      'ms': 'Isyarat: ',
      'fa': 'سیگنال: ',
      'so': 'Calaamadda: ',
      'ha': 'Alama: ',
      'sw': 'Mawimbi: ',
    },
    'alerts_history': {
      'ar': 'سجل التنبيهات',
      'en': 'Alerts History',
      'ur': 'تنبیہات کی تاریخ',
      'bn': 'সতর্কতার ইতিহাস',
      'tr': 'Uyarılar Geçmişi',
      'fr': 'Historique des alertes',
      'id': 'Riwayat Peringatan',
      'ms': 'Sejarah Amaran',
      'fa': 'تاریخچه هشدارها',
      'so': 'Taariikhda Digniinaha',
      'ha': 'Tarihin Faɗakarwa',
      'sw': 'Historia ya Tahadhari',
    },

    // ─── شاشة اختيار اللغة ───
    'select_lang': {
      'ar': 'اختر اللغة',
      'en': 'Select Language',
      'ur': 'زبان منتخب کریں',
      'bn': 'ভাষা নির্বাচন করুন',
      'tr': 'Dil Seçin',
      'fr': 'Choisir la Langue',
      'id': 'Pilih Bahasa',
      'ms': 'Pilih Bahasa',
      'fa': 'انتخاب زبان',
      'so': 'Xulo Luuqadda',
      'ha': 'Zaɓi Harshe',
      'sw': 'Chagua Lugha',
    },

    // ─── نصوص الإرشاد الصوتي والـ TTS للطواف والسعي ───
    'completion_speech_tawaf': {
      'ar': 'مَا شَاءَ اللَّهُ! أَتْمَمْتَ الطَّوَافَ كَامِلاً.',
      'en': 'Masha\'Allah! You have completed the Tawaf.',
      'ur': 'ماشاللہ! آپ نے طواف مکمل کر لیا ہے۔',
      'bn': 'মাশাআল্লাহ! আপনি তওয়াফ সম্পন্ন করেছেন।',
      'tr': 'Maşallah! Tavafı tamamladınız.',
      'fr': 'Masha\'Allah ! Vous avez terminé le Tawaf.',
      'id': 'Masya Allah! Anda telah menyelesaikan Tawaf.',
      'ms': 'Masya Allah! Anda telah menyelesaikan Tawaf.',
      'fa': 'ماشاءالله! طواف را کامل کردید.',
      'so': 'Masha\'Allah! Waxaad dhamaysay Daawafka.',
      'ha': 'Masha\'Allah! Kun kammala Tawafi.',
      'sw': 'Masha\'Allah! Umetimiza Tawaf.',
    },
    'completion_speech_sai': {
      'ar': 'مَا شَاءَ اللَّهُ! أَتْمَمْتَ السَّعْيَ كَامِلاً.',
      'en': 'Masha\'Allah! You have completed the Sa\'ee.',
      'ur': 'ماشاللہ! آپ نے سعی مکمل کر لی ہے۔',
      'bn': 'মাশাআল্লাহ! আপনি সাঈ সম্পন্ন করেছেন।',
      'tr': 'Maşallah! Sa\'yi tamamladınız.',
      'fr': 'Masha\'Allah ! Vous avez terminé le Sa\'ee.',
      'id': 'Masya Allah! Anda telah menyelesaikan Sa\'i.',
      'ms': 'Masya Allah! Anda telah menyelesaikan Sa\'ie.',
      'fa': 'ماشاءالله! سعی را کامل کردید.',
      'so': 'Masha\'Allah! Waxaad dhamaysay Sa\'yiga.',
      'ha': 'Masha\'Allah! Kun kammala Sa\'ayi.',
      'sw': 'Masha\'Allah! Umetimiza Sa\'i.',
    },

    // ─── نصوص التنبيهات في سجل الطوارئ (SOS Log) ───
    'alert_sender_you': {
      'ar': 'أنت',
      'en': 'You',
      'ur': 'آپ',
      'bn': 'আপনি',
      'tr': 'Siz',
      'fr': 'Vous',
      'id': 'Anda',
      'ms': 'Anda',
      'fa': 'شما',
      'so': 'Adiga',
      'ha': 'Kai',
      'sw': 'Wewe',
    },
    'alert_sender_peer': {
      'ar': 'حاج قريب',
      'en': 'Nearby Pilgrim',
      'ur': 'قریبی حاجی',
      'bn': 'কাছের হাজি',
      'tr': 'Yakın Hacı',
      'fr': 'Pèlerin Proche',
      'id': 'Jemaah Terdekat',
      'ms': 'Jemaah Berdekatan',
      'fa': 'حاجی نزدیک',
      'so': 'Xaji U Dhow',
      'ha': 'Mahajjaci Kusa',
      'sw': 'Haji wa Karibu',
    },
    'alert_msg_sent': {
      'ar': 'تم إرسال نداء استغاثة',
      'en': 'SOS Alert Sent',
      'ur': 'ہنگامی امداد کا پیغام بھیجا گیا',
      'bn': 'জরুরী সাহায্য বার্তা পাঠানো হয়েছে',
      'tr': 'SOS Uyarısı Gönderildi',
      'fr': 'Alerte SOS envoyée',
      'id': 'Peringatan SOS Terkirim',
      'ms': 'Amaran SOS Dihantar',
      'fa': 'هشدار SOS ارسال شد',
      'so': 'Digniinta SOS La Diray',
      'ha': 'An Aika Faɗakarwar SOS',
      'sw': 'Tahadhari ya SOS Imetumwa',
    },
    'alert_msg_received': {
      'ar': 'تم استلام ندائك — المساعدة في الطريق',
      'en': 'Your alert received — Help is on the way',
      'ur': 'آپ کا پیغام موصول ہوا — مدد راستے میں ہے',
      'bn': 'আপনার বার্তাটি পাওয়া গেছে — সাহায্য আসছে',
      'tr': 'Uyarınız alındı — Yardım yolda',
      'fr': 'Votre alerte a été reçue — L\'aide est en route',
      'id': 'Peringatan Anda diterima — Bantuan sedang dalam perjalanan',
      'ms': 'Amaran anda diterima — Bantuan dalam perjalanan',
      'fa': 'هشدار شما دریافت شد — کمک در راه است',
      'so': 'Digniintaada waa la helay — Gargaarku waa soo socdaa',
      'ha': 'An sami faɗakarwarku — Taimako na kan hanya',
      'sw': 'Tahadhari yako imepokewa — Msaada upo njiani',
    },

    // ─── الإرشاد الصوتي للطوارئ ───
    'sos_speech_sent': {
      'ar': 'تم إرسال نداء الطوارئ. جاري إبلاغ الحجاج القريبين منك.',
      'en': 'Emergency SOS sent. Notifying nearby pilgrims.',
      'ur': 'ہنگامی نداء بھیج دی گئی ہے۔ قریبی حجاج کو مطلع کیا جا رہا ہے۔',
      'bn': 'জরুরী এসওএস পাঠানো হয়েছে। আশেপাশের হাজীদের জানানো হচ্ছে।',
      'tr': 'Acil SOS gönderildi. Yakındaki hacılar bilgilendiriliyor.',
      'fr': 'SOS d\'urgence envoyé. Notification des pèlerins à proximité.',
      'id': 'SOS darurat dikirim. Memberi tahu jemaah terdekat.',
      'ms': 'SOS kecemasan dihantar. Memberitahu jemaah berdekatan.',
      'fa': 'پیام اضطراری ارسال شد. در حال اطلاع‌رسانی به حجاج نزدیک.',
      'so': 'SOS degdeg ah ayaa la diray. Waxaa la ogeysiinayaa xujayda u dhow.',
      'ha': 'An aika SOS na gaggawa. Ana sanar da mahajjata na kusa.',
      'sw': 'SOS ya dharura imetumwa. Inawaarifu mahujaji wa karibu.',
    },
    'sos_speech_received': {
      'ar': 'تم استلام ندائك من حاج قريب. المساعدة في الطريق إن شاء الله.',
      'en': 'Your alert has been received by a nearby pilgrim. Help is on the way, God willing.',
      'ur': 'قریبی حاجی سے آپ کا پیغام موصول ہو گیا ہے۔ ان شاء اللہ مدد راستے میں ہے۔',
      'bn': 'কাছের একজন হাজি আপনার বার্তাটি পেয়েছেন। ইনশাআল্লাহ সাহায্য আসছে।',
      'tr': 'Uyarınız yakın bir hacı tarafından alındı. İnşallah yardım yolda.',
      'fr': 'Votre alerte a été reçue par un pèlerin proche. L\'aide est en route, si Dieu le veut.',
      'id': 'Peringatan Anda telah diterima oleh jemaah terdekat. Bantuan sedang dalam perjalanan, insya Allah.',
      'ms': 'Amaran anda telah diterima oleh jemaah berdekatan. Bantuan dalam perjalanan, insya-Allah.',
      'fa': 'هشدار شما توسط یک حاجی نزدیک دریافت شد. ان‌شاءالله کمک در راه است.',
      'so': 'Digniintaada waxaa helay xaji u dhow. Gargaarku waa soo socdaa, haddii Eebbe idmo.',
      'ha': 'Wani mahajjaci na kusa ya sami faɗakarwarku. Taimako na kan hanya, in sha Allah.',
      'sw': 'Tahadhari yako imepokewa na mahujaji wa karibu. Msaada upo njiani, Mungu akipenda.',
    },
    'sos_speech_cancelled': {
      'ar': 'تم إلغاء نداء الطوارئ.',
      'en': 'Emergency SOS cancelled.',
      'ur': 'ہنگامی نداء منسوخ کر دی گئی ہے۔',
      'bn': 'জরুরী সাহায্য বাতিল করা হয়েছে।',
      'tr': 'Acil SOS iptal edildi.',
      'fr': 'SOS d\'urgence annulé.',
      'id': 'SOS darurat dibatalkan.',
      'ms': 'SOS kecemasan dibatalkan.',
      'fa': 'پیام اضطراری لغو شد.',
      'so': 'SOS degdeg ah waa la joojiyay.',
      'ha': 'An soke SOS na gaggawa.',
      'sw': 'SOS ya dharura imeghairiwa.',
    },

    // ─── خريطة مكة والموقع ───
    'map_nav_auto_tracking': {
      'ar': 'جاري تتبع موقعك التلقائي وحساب أقرب الخدمات...',
      'en': 'Automatically tracking your location and calculating nearest services...',
      'ur': 'خودکار طریقے سے آپ کا مقام ٹریک کیا جا رہا ہے اور قریبی خدمات का हिसाब लगाया जा रहा है...',
      'bn': 'স্বয়ংক্রিয়ভাবে আপনার অবস্থান ট্র্যাক করা হচ্ছে এবং নিকটতম পরিষেবাগুলি গণনা করা হচ্ছে...',
      'tr': 'Konumunuz otomatik olarak izleniyor ve en yakın hizmetler hesaplanıyor...',
      'fr': 'Suivi automatique de votre position et calcul des services les plus proches...',
      'id': 'Melacak lokasi Anda secara otomatis dan menghitung layanan terdekat...',
      'ms': 'Menjejaki lokasi anda secara automatik dan mengira perkhidmatan terdekat...',
      'fa': 'ردیابی خودکار موقعیت شما و محاسبه نزدیک‌ترین خدمات...',
      'so': 'Si toos ah ula socoshada goobtaada iyo xisaabinta adeegyada ugu dhow...',
      'ha': 'Ana bin wurinka ta atomatik da kuma lissafin sabis mafi kusa...',
      'sw': 'Kufuatilia eneo lako kiotomatiki na kuhesabu huduma za karibu...',
    },
    'map_nav_sim_mode': {
      'ar': 'وضع المحاكاة نشط 🌐\nاضغط على أي مكان بالخريطة لتحديد موقعك الافتراضي وحساب الخدمة.',
      'en': 'Simulation mode active 🌐\nTap anywhere on the map to set your virtual location and calculate the nearest service.',
      'ur': 'محاكاة موڈ فعال ہے 🌐\nاپنا فرضی مقام متعین کرنے اور قریبی خدمت کا حساب لگانے کے لیے نقشے پر کہیں भी ٹیپ کریں۔',
      'bn': 'সিমুলেশন মোড সক্রিয় 🌐\nআপনার ভার্চুয়াল অবস্থান নির্ধারণ করতে এবং নিকটতম পরিষেবা গণনা করতে মানচিত্রের যেকোনো স্থানে ট্যাপ করুন।',
      'tr': 'Simülasyon modu aktif 🌐\nSanal konumunuzu ayarlamak ve en yakın hizmeti hesaplamak için haritada herhangi bir yere dokunun.',
      'fr': 'Mode simulation actif 🌐\nAppuyez n\'importe où sur la carte pour définir votre position virtuelle et calculer le service le plus proche.',
      'id': 'Mode simulasi aktif 🌐\nKetuk di mana saja pada peta untuk menentukan lokasi virtual Anda dan menghitung layanan terdekat.',
      'ms': 'Mod simulasi aktif 🌐\nKetik di mana-mana sahaja pada peta untuk tetapkan lokasi maya anda dan mengira perkhidmatan terdekat.',
      'fa': 'حالت شبیه‌سازی فعال است 🌐\nبرای تنظیم موقعیت مجازی خود و محاسبه نزدیک‌ترین خدمات، هر جایی از نقشه را ضربه بزنید.',
      'so': 'Habka muujinta waa shaqaynayaa 🌐\nTaabo meel kasta oo khariidadda ah si aad u dejiso goobtaada khiyaalka ah una xisaabiso adeegga ugu dhow.',
      'ha': 'Yanayin kwaikwayo yana aiki 🌐\nDanna ko\'ina a taswira don saita wurinka na kwaikwayo da lissafin sabis mafi kusa.',
      'sw': 'Hali ya uigaji inafanya kazi 🌐\nGusa popote kwenye ramani ili kuweka eneo lako la kufikirika na kuhesabu huduma iliyo karibu.',
    },
    'default_service_point': {
      'ar': 'نقطة خدمة',
      'en': 'Service Point',
      'ur': 'سروس پوائنٹ',
      'bn': 'সেবা কেন্দ্র',
      'tr': 'Hizmet Noktası',
      'fr': 'Point de service',
      'id': 'Titik Layanan',
      'ms': 'Titik Perkhidmatan',
      'fa': 'نقطه خدمات',
      'so': 'Meesha Adeegga',
      'ha': 'Wurin Sabis',
      'sw': 'Kituo cha Huduma',
    },
    'map_nav_success_prefix': {
      'ar': 'الموقع المحدد بنجاح 📍\nأقرب نقطة خدمية: ',
      'en': 'Location set successfully 📍\nNearest service point: ',
      'ur': 'مقام کامیابی سے متعین ہو گیا 📍\nقریب ترین سروس پوائنٹ: ',
      'bn': 'অবস্থান সফলভাবে সেট করা হয়েছে 📍\nনিকটতম পরিষেবা কেন্দ্র: ',
      'tr': 'Konum başarıyla ayarlandı 📍\nEn yakın hizmet noktası: ',
      'fr': 'Position définie avec succès 📍\nPoint de service le plus proche : ',
      'id': 'Lokasi berhasil diatur 📍\nTitik layanan terdekat: ',
      'ms': 'Lokasi berjaya ditetapkan 📍\nTitik perkhidmatan terdekat: ',
      'fa': 'موقعیت با موفقیت تنظیم شد 📍\nنزدیک‌ترین نقطه خدمات: ',
      'so': 'Goobta si guul leh ayaa loo dejiyay 📍\nKituo adeegga ugu dhow: ',
      'ha': 'An saita wuri cikin nasara 📍\nWurin sabis mafi kusa: ',
      'sw': 'Mahali pamewekwa kwa mafanikio 📍\nKituo cha huduma kilicho karibu: ',
    },
    'map_nav_distance_prefix': {
      'ar': ' وتبعد ',
      'en': ' and is away ',
      'ur': ' اور وہ دور ہے ',
      'bn': ' এবং দূরে অবস্থিত ',
      'tr': ' ve uzaklıkta ',
      'fr': ' et se trouve à ',
      'id': ' dan berjarak ',
      'ms': ' dan berjarak ',
      'fa': ' و در فاصله ',
      'so': ' oo u jirta ',
      'ha': ' kuma nisa ',
      'sw': ' na iko umbali wa ',
    },
    'map_speech_nearest_prefix': {
      'ar': 'تم تحديد موقعك. أقرب نقطة لك هي ',
      'en': 'Your location is set. The nearest point to you is ',
      'ur': 'آپ کا مقام متعین ہو گیا ہے۔ آپ کے قریب ترین مقام ',
      'bn': 'আপনার অবস্থান সেট করা হয়েছে। আপনার নিকটতম স্থানটি হলো ',
      'tr': 'Konumunuz belirlendi. Size en yakın nokta ',
      'fr': 'Votre position est définie. Le point le plus proche de vous est ',
      'id': 'Lokasi Anda telah ditentukan. Titik terdekat dari Anda adalah ',
      'ms': 'Lokasi anda telah ditentukan. Titik terdekat dengan anda ialah ',
      'fa': 'موقعیت شما تعیین شد. نزدیک‌ترین نقطه به شما ',
      'so': 'Goobtaada waa la dejiyay. Meesha kuugu dhow waa ',
      'ha': 'An saita wurinka. Wurin da ya fi kusa da kai shi ne ',
      'sw': 'Mahali pako pamewekwa. Kituo kilicho karibu zaidi nawe ni ',
    },
    'map_speech_distance_prefix': {
      'ar': ' والمسافة إليها تبلغ حوالي ',
      'en': ' and the distance to it is about ',
      'ur': ' ہے اور اس تک فاصلہ تقریباً ',
      'bn': ' এবং এর দূরত্ব প্রায় ',
      'tr': ' ve ona olan mesafe yaklaşık ',
      'fr': ' et la distance pour y accéder est d\'environ ',
      'id': ' dan jarak ke sana sekitar ',
      'ms': ' dan jarak ke sana sekitar ',
      'fa': ' است و فاصله تا آن حدود ',
      'so': ' fogaanteeduna waa qiyaastii ',
      'ha': ' kuma nisa zuwa gare shi ya kai kusan ',
      'sw': ' na umbali wake ni karibu ',
    },

    // ─── أسماء نقاط الخدمات المتواجدة في مكة ───
    'point_hospital_ajyad': {
      'ar': 'مستشفى أجياد الدولي',
      'en': 'Ajyad International Hospital',
      'ur': 'اجیاد انٹرنیشنل ہسپتال',
      'bn': 'আজিয়اد ইন্টারন্যাশনাল হাসপাতাল',
      'tr': 'Ajyad Uluslararası Hastanesi',
      'fr': 'Hôpital International Ajyad',
      'id': 'Rumah Sakit Internasional Ajyad',
      'ms': 'Hospital Antarabangsa Ajyad',
      'fa': 'بیمارستان بین‌المللی اجیاد',
      'so': 'Cisbitaalka Caalamiga ah ee Ajyad',
      'ha': 'Asibitin Ajyad na Duniya',
      'sw': 'Hospitali ya Kimataifa ya Ajyad',
    },
    'point_hospital_aziz': {
      'ar': 'مستشفى الملك عبدالعزيز',
      'en': 'King Abdulaziz Hospital',
      'ur': 'ملک عبدالعزیز ہسپتال',
      'bn': 'কিং আব্দুল আজিজ হাসপাতাল',
      'tr': 'Kral Abdulaziz Hastanesi',
      'fr': 'Hôpital Roi Abdulaziz',
      'id': 'Rumah Sakit Raja Abdulaziz',
      'ms': 'Hospital Raja Abdulaziz',
      'fa': 'بیمارستان ملک عبدالعزیز',
      'so': 'Cisbitaalka Boqor Abdulaziz',
      'ha': 'Asibitin Sarki Abdulaziz',
      'sw': 'Hospitali ya Mfalme Abdulaziz',
    },
    'point_ambulance_haram': {
      'ar': 'مركز إسعاف المسجد الحرام',
      'en': 'Al-Masjid Al-Haram First Aid',
      'ur': 'مسجد الحرام فرسٹ ایڈ سینٹر',
      'bn': 'মসজিদুল হারাম ফার্স্ট এইড সেন্টার',
      'tr': 'Mescid-i Haram İlk Yardım Merkezi',
      'fr': 'Premiers Secours de la Grande Mosquée',
      'id': 'Pertolongan Pertama Masjidil Haram',
      'ms': 'Pertolongan Cemas Masjidil Haram',
      'fa': 'مرکز کمک‌های اولیه مسجدالحرام',
      'so': 'Gargaarka Degdegga ee Masjidul Xaraam',
      'ha': 'Taimakon Farko na Masallacin Al-Haram',
      'sw': 'Huduma ya Kwanza Msikiti Al-Haram',
    },
    'point_ambulance_safa': {
      'ar': 'نقطة إسعاف الصفا',
      'en': 'Al-Safa First Aid Point',
      'ur': 'صفا فرسٹ ایڈ پوائنٹ',
      'bn': 'সাফা ফার্স্ট এইড পয়েন্ট',
      'tr': 'Safa İlk Yardım Noktası',
      'fr': 'Point de Premiers Secours Al-Safa',
      'id': 'Pos Pertolongan Pertama Al-Safa',
      'ms': 'Pos Pertolongan Cemas Al-Safa',
      'fa': 'نقطه کمک‌های اولیه صفا',
      'so': 'Meesha Gargaarka Degdegga ee Al-Safa',
      'ha': 'Wurin Taimakon Farko na Al-Safa',
      'sw': 'Kituo cha Huduma ya Kwanza Al-Safa',
    },
    'point_water_salam': {
      'ar': 'نقطة مياه — باب السلام',
      'en': 'Water Point — Bab Al-Salam',
      'ur': 'پانی کی سبیل — باب السلام',
      'bn': 'পানির কল — বাব আস-সালাম',
      'tr': 'Su Noktası — Babü\'s-Selam',
      'fr': 'Point d\'eau — Bab Al-Salam',
      'id': 'Titik Air — Babus Salam',
      'ms': 'Titik Air — Babus Salam',
      'fa': 'ایستگاه آب — باب‌السلام',
      'so': 'Goobta Biyaha — Bab Al-Salam',
      'ha': 'Wurin Ruwa — Kofar Al-Salam',
      'sw': 'Kituo cha Maji — Bab Al-Salam',
    },
    'point_water_masaa': {
      'ar': 'نقطة مياه — المسعى',
      'en': 'Water Point — Al-Masa\'a',
      'ur': 'پانی کی سبیل — المسعى',
      'bn': 'পানির কল — আল-মাসআ',
      'tr': 'Su Noktası — Mes\'a',
      'fr': 'Point d\'eau — Al-Masa\'a',
      'id': 'Titik Air — Masa\'a',
      'ms': 'Titik Air — Masa\'ie',
      'fa': 'ایستگاه آب — مسعی',
      'so': 'Goobta Biyaha — Al-Masa\'a',
      'ha': 'Wurin Ruwa — Al-Masa\'a',
      'sw': 'Kituo cha Maji — Al-Masa\'a',
    },
    'point_shade_ajyad': {
      'ar': 'منطقة مظللة — أجياد',
      'en': 'Shaded Area — Ajyad',
      'ur': 'سایہ دار جگہ — اجیاد',
      'bn': 'ছায়াযুক্ত স্থান — আজিয়اد',
      'tr': 'Gölgelik Alan — Ajyad',
      'fr': 'Zone Ombragée — Ajyad',
      'id': 'Area Teduh — Ajyad',
      'ms': 'Kawasan Teduh — Ajyad',
      'fa': 'منطقه سایه‌دار — اجیاد',
      'so': 'Meesha Hooska — Ajyad',
      'ha': 'Wurin Inuwa — Ajyad',
      'sw': 'Eneo la Kivuli — Ajyad',
    },
    'point_shade_marwah': {
      'ar': 'منطقة مظللة — المروة',
      'en': 'Shaded Area — Al-Marwah',
      'ur': 'سایہ دار جگہ — المروہ',
      'bn': 'ছায়াযুক্ত স্থান — আল-মারওয়াহ',
      'tr': 'Gölgelik Alan — Merve',
      'fr': 'Zone Ombragée — Al-Marwah',
      'id': 'Area Teduh — Al-Marwah',
      'ms': 'Kawasan Teduh — Al-Marwah',
      'fa': 'منطقه سایه‌دار — مروه',
      'so': 'Meesha Hooska — Al-Marwah',
      'ha': 'Wurin Inuwa — Al-Marwah',
      'sw': 'Eneo la Kivuli — Al-Marwah',
    },
  };

  // تحميل اللغة المحفوظة عند فتح التطبيق
  static Future<void> loadSavedLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    currentLang = prefs.getString('lang') ?? 'ar';
  }

  static Future<void> setLanguage(String lang) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('lang', lang);
    currentLang = lang;
  }

  static String translate(String key) {
    return translations[key]?[currentLang] ??
        translations[key]?['ar'] ??
        key;
  }

  // دالة ذكية لإرجاع كود لغة الصوت (TTS) بناءً على اختيار الحاج الحالي
  static String getTtsLanguageCode() {
    switch (currentLang) {
      case 'en':
        return 'en-US';
      case 'ur':
        return 'ur-PK';
      case 'bn':
        return 'bn-BD';
      case 'tr':
        return 'tr-TR';
      case 'fr':
        return 'fr-FR';
      case 'id':
        return 'id-ID';
      case 'ms':
        return 'ms-MY';
      case 'fa':
        return 'fa-IR';
      case 'so':
        return 'so-SO';
      case 'ha':
        return 'ha';
      case 'sw':
        return 'sw-KE';
      case 'ar':
      default:
        return 'ar';
    }
  }
}